import { Injectable, inject } from '@angular/core';
import { Observable, of, map } from 'rxjs';
import { Lista, CategoriaLiturgica, ListasDoDiaResponse } from '../models/lista.model';
import { ListaRepository } from './lista.repository';
import { CifraRepository, CifraIndiceItem } from './cifra.repository';

const LS_ALL_KEY = 'listas_mock_all';

// 384 músicas importadas de musicasparamissa.com.br
const MOCK_LISTAS: Lista[] = [
  {
    id: 'lista-missa-do-dia-–-domingo-do-tempo-comum',
    titulo: 'Missa do Dia – Domingo do Tempo Comum',
    data: '2026-05-04',
    categoria: 'tempo-comum',
    musicas: [
      {
        id: 'm-aclamacoes-a-oracao-eucaristica-i-padre-wallison-rodrigues-ato-penitencial',
        cifraId: 'aclamacoes-a-oracao-eucaristica-i-padre-wallison-rodrigues',
        nome: 'Aclamações À Oracao Eucaristica I',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-aclamacoes-a-oracao-eucaristica-ii-robson-medeiros-vicente-ato-penitencial',
        cifraId: 'aclamacoes-a-oracao-eucaristica-ii-robson-medeiros-vicente',
        nome: 'Aclamações À Oração Eucarística Ii',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
    ],
    criadaEm: '2026-05-04T08:00:00Z',
    atualizadaEm: '2026-05-04T08:00:00Z',
  },
  {
    id: 'lista-missa-das-10h-–-família',
    titulo: 'Missa das 10h – Família',
    data: '2026-05-04',
    categoria: 'tempo-comum',
    musicas: [
      {
        id: 'm-a-alegria-esta-coracao-entrada',
        cifraId: 'a-alegria-esta-coracao',
        nome: 'A Alegria Está No Coração',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-bendito-sejais-coral-palestrina-entrada',
        cifraId: 'bendito-sejais-coral-palestrina',
        nome: 'Bendito Sejais',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-a-mesa-santa-que-preparamos-ato-penitencial',
        cifraId: 'a-mesa-santa-que-preparamos',
        nome: 'A Mesa Santa Que Preparamos',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-bendito-sejais-senhor-ato-penitencial',
        cifraId: 'bendito-sejais-senhor',
        nome: 'Bendito Sejais, Senhor!',
        autor: 'PADRE JOSÉ WEBER',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-a-palavra-de-deus-que-gera-a-vida-gloria',
        cifraId: 'a-palavra-de-deus-que-gera-a-vida',
        nome: 'A Palavra De Deus Que Gera A Vida',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-brilha-uma-luz-gloria',
        cifraId: 'brilha-uma-luz',
        nome: 'Brilha Uma Luz',
        autor: 'IRMÃ MIRIA KOLLING',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-a-palavra-de-deus-e-luz-salmo',
        cifraId: 'a-palavra-de-deus-e-luz',
        nome: 'A Palavra De Deus É Luz',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-canto-louvores-ao-pai-salmo',
        cifraId: 'canto-louvores-ao-pai',
        nome: 'Canto Louvores Ao Pai',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-a-hostia-sobre-o-altar-ofertorio',
        cifraId: 'a-hostia-sobre-o-altar',
        nome: 'A Hóstia Sobre O Altar',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-aviagem-ofertorio',
        cifraId: 'aviagem',
        nome: 'A Viagem',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-augusta-rainha-santo',
        cifraId: 'augusta-rainha',
        nome: 'Augusta Rainha',
        autor: 'ALINE BRASIL',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-de-maos-estendidas-santo',
        cifraId: 'de-maos-estendidas',
        nome: 'De Mãos Estendidas',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 1,
      },
      {
        id: 'm-bendigamos-ao-senhor-marcelo-oliveira-comunhao',
        cifraId: 'bendigamos-ao-senhor-marcelo-oliveira',
        nome: 'Bendigamos Ao Senhor',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-deixa-a-luz-do-ceu-entrar-comunhao',
        cifraId: 'deixa-a-luz-do-ceu-entrar',
        nome: 'Deixa A Luz Do Céu Entrar',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-bendito-seja-deus-final',
        cifraId: 'bendito-seja-deus',
        nome: 'Bendito Seja Deus',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-desde-o-nascer-ao-por-do-sol-final',
        cifraId: 'desde-o-nascer-ao-por-do-sol',
        nome: 'Desde O Nascer Ao Por Do Sol',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 1,
      },
    ],
    criadaEm: '2026-05-04T08:00:00Z',
    atualizadaEm: '2026-05-04T08:00:00Z',
  },
  {
    id: 'lista-quarta-feira-de-cinzas',
    titulo: 'Quarta-feira de Cinzas',
    data: '2026-05-03',
    categoria: 'quaresma',
    musicas: [
      {
        id: 'm-a-abstinencia-quaresmal-entrada',
        cifraId: 'a-abstinencia-quaresmal',
        nome: 'A Abstinência Quaresmal',
        autor: 'FREI JOAQUIM FONSECA, OFM',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-nossos-dons-apresentamos-entrada',
        cifraId: 'nossos-dons-apresentamos',
        nome: 'Nossos Dons Apresentamos',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-aceita-senhor-com-prazer-ato-penitencial',
        cifraId: 'aceita-senhor-com-prazer',
        nome: 'Aceita Senhor Com Prazer',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-o-vosso-coracao-de-pedra-paulus-ato-penitencial',
        cifraId: 'o-vosso-coracao-de-pedra-paulus',
        nome: 'O Vosso Coração De Pedra',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-bendito-és-tu-o-deus-criador-gloria',
        cifraId: 'bendito-és-tu-o-deus-criador',
        nome: 'Bendito És Tu, Ó Deus Criador',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-pela-compaixao-tocados-gloria',
        cifraId: 'pela-compaixao-tocados',
        nome: 'Pela Compaixão Tocados',
        autor: 'Fr. Wanderson Luiz Freitas, O.Carm.',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-criai-em-nos-um-coracao-que-seja-puro-salmo',
        cifraId: 'criai-em-nos-um-coracao-que-seja-puro',
        nome: 'Criai Em Nós Um Coração Que Seja Puro',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-pra-sempre-se-bendito-salmo',
        cifraId: 'pra-sempre-se-bendito',
        nome: 'Pra Sempre Sê Bendito',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-escuta-senhor-ofertorio',
        cifraId: 'escuta-senhor',
        nome: 'Escuta Senhor',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-queremos-oferecer-ofertorio',
        cifraId: 'queremos-oferecer',
        nome: 'Queremos Oferecer',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-este-sacrificio-de-louvor-santo',
        cifraId: 'este-sacrificio-de-louvor',
        nome: 'Este Sacrifício De Louvor',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-fala-senhor-tiago-gonçalves-comunhao',
        cifraId: 'fala-senhor-tiago-gonçalves',
        nome: 'Fala Senhor!',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-hino-da-campanha-da-fraternidade-2026-final',
        cifraId: 'hino-da-campanha-da-fraternidade-2026',
        nome: 'Hino Oficial Da Campanha Da Fraternidade 2026',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-lembra-senhor-o-teu-amor-final',
        cifraId: 'lembra-senhor-o-teu-amor',
        nome: 'Lembra Senhor, O Teu Amor',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 1,
      },
    ],
    criadaEm: '2026-05-03T08:00:00Z',
    atualizadaEm: '2026-05-03T08:00:00Z',
  },
  {
    id: 'lista-primeiro-domingo-do-advento',
    titulo: 'Primeiro Domingo do Advento',
    data: '2026-05-05',
    categoria: 'advento',
    musicas: [
      {
        id: 'm-nossa-oferta-apresentamos-entrada',
        cifraId: 'nossa-oferta-apresentamos',
        nome: 'A Nossa Oferta Apresentamos',
        autor: 'FREI JOEL POSTMA',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-senhor-nos-te-esperamos-entrada',
        cifraId: 'senhor-nos-te-esperamos',
        nome: 'Senhor Nós Te Esperamos',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-abencoa-ato-penitencial',
        cifraId: 'abencoa',
        nome: 'Abençoa',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-tempo-de-esperanca-e-de-viver-ato-penitencial',
        cifraId: 'tempo-de-esperanca-e-de-viver',
        nome: 'Tempo De Esperança E De Viver',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-ficai-atentos-e-orai-paulo-neto-gloria',
        cifraId: 'ficai-atentos-e-orai-paulo-neto',
        nome: 'Ficai Atentos E Orai',
        autor: 'Paulo Neto',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-nasceu-em-belem-casa-pao-salmo',
        cifraId: 'nasceu-em-belem-casa-pao',
        nome: 'Nasceu Em Belém, A Casa Do Pão',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-os-que-esperam-no-senhor-paulo-neto-ofertorio',
        cifraId: 'os-que-esperam-no-senhor-paulo-neto',
        nome: 'Os Que Esperam No Senhor',
        autor: 'PAULO NETO',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-os-que-vos-esperam-o-senhor-cantando-antifonas-santo',
        cifraId: 'os-que-vos-esperam-o-senhor-cantando-antifonas',
        nome: 'Os Que Vos Esperam, Ó Senhor',
        autor: 'RUZYE (CANTANDO ANTÍFONAS)',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-pao-e-vinho-apresentamos-comunhao',
        cifraId: 'pao-e-vinho-apresentamos',
        nome: 'Pão E Vinho Apresentamos',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-da-cepa-brotou-rama-final',
        cifraId: 'da-cepa-brotou-rama',
        nome: 'Da Cepa Brotou A Rama',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-espera-o-povo-um-menino-grupo-opa-final',
        cifraId: 'espera-o-povo-um-menino-grupo-opa',
        nome: 'Espera O Povo Um Menino',
        autor: 'PE. IRALA · LUISINHO VIEIRA',
        parte: 'final',
        ordem: 1,
      },
    ],
    criadaEm: '2026-05-05T08:00:00Z',
    atualizadaEm: '2026-05-05T08:00:00Z',
  },
  {
    id: 'lista-vigília-pascal',
    titulo: 'Vigília Pascal',
    data: '2026-05-10',
    categoria: 'pascoa',
    musicas: [
      {
        id: 'm-mesa-tao-grande-entrada',
        cifraId: 'mesa-tao-grande',
        nome: 'A Mesa Tão Grande',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-amou-nos-ate-o-fim-entrada',
        cifraId: 'amou-nos-ate-o-fim',
        nome: 'Amou Nos Até O Fim',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-aleluia-ato-penitencial',
        cifraId: 'aleluia',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal - Eliomar Ribeiro',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-antes-da-morte-e-ressurreicao-de-jesus-ato-penitencial',
        cifraId: 'antes-da-morte-e-ressurreicao-de-jesus',
        nome: 'Antes Da Morte E Ressurreição De Jesus',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-arq-goiania-gloria',
        cifraId: 'aleluia-o-nosso-cordeiro-arq-goiania',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-cantai-ao-senhor-deus-um-canto-novo-gloria',
        cifraId: 'cantai-ao-senhor-deus-um-canto-novo',
        nome: 'Cantai Ao Senhor Deus Um Canto Novo',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-salmo',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal - Frei Fabreti',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-sequencia-pascal-cantai-cristaos-afinal-salmo',
        cifraId: 'sequencia-pascal-cantai-cristaos-afinal',
        nome: 'Cantai Cristãos, Afinal',
        autor: 'PE JOSÉ WEBER',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-2-ofertorio',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal-2',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-cantai-cristaos-afinal-comunidade-recado-ofertorio',
        cifraId: 'cantai-cristaos-afinal-comunidade-recado',
        nome: 'Cantai, Cristãos, Afinal',
        autor: 'ANDRÉ ZAMUR',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-cantos-liturgicos-santo',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal-cantos-liturgicos',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-celebremos-a-festa-comunidade-recado-santo',
        cifraId: 'celebremos-a-festa-comunidade-recado',
        nome: 'Celebremos A Festa',
        autor: 'MARCELO OLIVEIRA',
        parte: 'santo',
        ordem: 1,
      },
      {
        id: 'm-aleluia-recitativos-capella-comunhao',
        cifraId: 'aleluia-recitativos-capella',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro - Banda Capella',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-cristo-ressuscitou-aleluia-comunhao',
        cifraId: 'cristo-ressuscitou-aleluia',
        nome: 'Cristo Ressuscitou, Aleluia!',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-aleluia-ressuscitei-o-pai-gilson-celerino-final',
        cifraId: 'aleluia-ressuscitei-o-pai-gilson-celerino',
        nome: 'Aleluia, Ressuscitei, Ó Pai',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-deus-cumpriu-a-promessa-a-nossos-pais-final',
        cifraId: 'deus-cumpriu-a-promessa-a-nossos-pais',
        nome: 'Deus Cumpriu A Promessa A Nossos Pais',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'final',
        ordem: 1,
      },
    ],
    criadaEm: '2026-05-10T08:00:00Z',
    atualizadaEm: '2026-05-10T08:00:00Z',
  },
  {
    id: 'lista-quaresma-–-músicas-do-jejum',
    titulo: 'Quaresma – Músicas do Jejum',
    data: undefined,
    categoria: 'quaresma',
    musicas: [
      {
        id: 'm-a-abstinencia-quaresmal-entrada',
        cifraId: 'a-abstinencia-quaresmal',
        nome: 'A Abstinência Quaresmal',
        autor: 'FREI JOAQUIM FONSECA, OFM',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-nossos-dons-apresentamos-entrada',
        cifraId: 'nossos-dons-apresentamos',
        nome: 'Nossos Dons Apresentamos',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-se-bendito-senhor-entrada',
        cifraId: 'se-bendito-senhor',
        nome: 'Sê Bendito Senhor',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 2,
      },
      {
        id: 'm-aceita-senhor-com-prazer-ato-penitencial',
        cifraId: 'aceita-senhor-com-prazer',
        nome: 'Aceita Senhor Com Prazer',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-o-vosso-coracao-de-pedra-paulus-ato-penitencial',
        cifraId: 'o-vosso-coracao-de-pedra-paulus',
        nome: 'O Vosso Coração De Pedra',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-bendito-és-tu-o-deus-criador-gloria',
        cifraId: 'bendito-és-tu-o-deus-criador',
        nome: 'Bendito És Tu, Ó Deus Criador',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-pela-compaixao-tocados-gloria',
        cifraId: 'pela-compaixao-tocados',
        nome: 'Pela Compaixão Tocados',
        autor: 'Fr. Wanderson Luiz Freitas, O.Carm.',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-criai-em-nos-um-coracao-que-seja-puro-salmo',
        cifraId: 'criai-em-nos-um-coracao-que-seja-puro',
        nome: 'Criai Em Nós Um Coração Que Seja Puro',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-pra-sempre-se-bendito-salmo',
        cifraId: 'pra-sempre-se-bendito',
        nome: 'Pra Sempre Sê Bendito',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-escuta-senhor-ofertorio',
        cifraId: 'escuta-senhor',
        nome: 'Escuta Senhor',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-queremos-oferecer-ofertorio',
        cifraId: 'queremos-oferecer',
        nome: 'Queremos Oferecer',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-este-sacrificio-de-louvor-santo',
        cifraId: 'este-sacrificio-de-louvor',
        nome: 'Este Sacrifício De Louvor',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-recebe-deus-amigo-santo',
        cifraId: 'recebe-deus-amigo',
        nome: 'Recebe, Deus Amigo',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 1,
      },
      {
        id: 'm-fala-senhor-tiago-gonçalves-comunhao',
        cifraId: 'fala-senhor-tiago-gonçalves',
        nome: 'Fala Senhor!',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-santo-cantando-antifonas-comunhao',
        cifraId: 'santo-cantando-antifonas',
        nome: 'Santo',
        autor: 'Ruzye',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-hino-da-campanha-da-fraternidade-2026-final',
        cifraId: 'hino-da-campanha-da-fraternidade-2026',
        nome: 'Hino Oficial Da Campanha Da Fraternidade 2026',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-lembra-senhor-o-teu-amor-final',
        cifraId: 'lembra-senhor-o-teu-amor',
        nome: 'Lembra Senhor, O Teu Amor',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 1,
      },
      {
        id: 'm-no-silencio-do-coracao-irma-miria-final',
        cifraId: 'no-silencio-do-coracao-irma-miria',
        nome: 'No Silêncio Do Coração',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 2,
      },
    ],
    criadaEm: '2025-01-01T00:00:00Z',
    atualizadaEm: '2025-01-01T00:00:00Z',
  },
  {
    id: 'lista-tempo-pascal-–-aleluia!',
    titulo: 'Tempo Pascal – Aleluia!',
    data: undefined,
    categoria: 'pascoa',
    musicas: [
      {
        id: 'm-mesa-tao-grande-entrada',
        cifraId: 'mesa-tao-grande',
        nome: 'A Mesa Tão Grande',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-amou-nos-ate-o-fim-entrada',
        cifraId: 'amou-nos-ate-o-fim',
        nome: 'Amou Nos Até O Fim',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-eis-que-faco-todas-as-coisas-entrada',
        cifraId: 'eis-que-faco-todas-as-coisas',
        nome: 'Eis Que Faço Novas Todas As Coisas',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 2,
      },
      {
        id: 'm-aleluia-ato-penitencial',
        cifraId: 'aleluia',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal - Eliomar Ribeiro',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-antes-da-morte-e-ressurreicao-de-jesus-ato-penitencial',
        cifraId: 'antes-da-morte-e-ressurreicao-de-jesus',
        nome: 'Antes Da Morte E Ressurreição De Jesus',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-era-preciso-marcelo-oliveira-ato-penitencial',
        cifraId: 'era-preciso-marcelo-oliveira',
        nome: 'Era Preciso',
        autor: 'MARCELO OLIVEIRA',
        parte: 'ato-penitencial',
        ordem: 2,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-arq-goiania-gloria',
        cifraId: 'aleluia-o-nosso-cordeiro-arq-goiania',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-cantai-ao-senhor-deus-um-canto-novo-gloria',
        cifraId: 'cantai-ao-senhor-deus-um-canto-novo',
        nome: 'Cantai Ao Senhor Deus Um Canto Novo',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-eu-vim-para-que-todos-tenha-vida-gloria',
        cifraId: 'eu-vim-para-que-todos-tenha-vida',
        nome: 'Eu Vim Para Que Todos Tenham Vida',
        autor: 'REGINALDO VELOSO',
        parte: 'gloria',
        ordem: 2,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-salmo',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal - Frei Fabreti',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-sequencia-pascal-cantai-cristaos-afinal-salmo',
        cifraId: 'sequencia-pascal-cantai-cristaos-afinal',
        nome: 'Cantai Cristãos, Afinal',
        autor: 'PE JOSÉ WEBER',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-fica-conosco-senhor-salmo',
        cifraId: 'fica-conosco-senhor',
        nome: 'Fica Conosco, Senhor',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'salmo',
        ordem: 2,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-2-ofertorio',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal-2',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-cantai-cristaos-afinal-comunidade-recado-ofertorio',
        cifraId: 'cantai-cristaos-afinal-comunidade-recado',
        nome: 'Cantai, Cristãos, Afinal',
        autor: 'ANDRÉ ZAMUR',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-imensa-alegria-ofertorio',
        cifraId: 'imensa-alegria',
        nome: 'Imensa Alegria',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 2,
      },
      {
        id: 'm-aleluia-o-nosso-cordeiro-pascal-cantos-liturgicos-santo',
        cifraId: 'aleluia-o-nosso-cordeiro-pascal-cantos-liturgicos',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro Pascal',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-celebremos-a-festa-comunidade-recado-santo',
        cifraId: 'celebremos-a-festa-comunidade-recado',
        nome: 'Celebremos A Festa',
        autor: 'MARCELO OLIVEIRA',
        parte: 'santo',
        ordem: 1,
      },
      {
        id: 'm-celebremos-nossa-pascoa-santo',
        cifraId: 'celebremos-nossa-pascoa',
        nome: 'Celebremos Nossa Páscoa',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 2,
      },
      {
        id: 'm-aleluia-recitativos-capella-comunhao',
        cifraId: 'aleluia-recitativos-capella',
        nome: 'Aleluia',
        autor: 'O Nosso Cordeiro - Banda Capella',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-cristo-ressuscitou-aleluia-comunhao',
        cifraId: 'cristo-ressuscitou-aleluia',
        nome: 'Cristo Ressuscitou, Aleluia!',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-la-do-ceu-pronunciastes-a-sentenca-comunhao',
        cifraId: 'la-do-ceu-pronunciastes-a-sentenca',
        nome: 'Lá Do Céu Pronunciastes A Sentença',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'comunhao',
        ordem: 2,
      },
      {
        id: 'm-aleluia-ressuscitei-o-pai-gilson-celerino-final',
        cifraId: 'aleluia-ressuscitei-o-pai-gilson-celerino',
        nome: 'Aleluia, Ressuscitei, Ó Pai',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-deus-cumpriu-a-promessa-a-nossos-pais-final',
        cifraId: 'deus-cumpriu-a-promessa-a-nossos-pais',
        nome: 'Deus Cumpriu A Promessa A Nossos Pais',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'final',
        ordem: 1,
      },
      {
        id: 'm-na-verdade-o-cristo-ressuscitou-aleluia-final',
        cifraId: 'na-verdade-o-cristo-ressuscitou-aleluia',
        nome: 'Na Verdade O Cristo Ressuscitou, Aleluia',
        autor: 'PAULO KEMP E THAYSSA GODÊNCIO',
        parte: 'final',
        ordem: 2,
      },
    ],
    criadaEm: '2025-01-01T00:00:00Z',
    atualizadaEm: '2025-01-01T00:00:00Z',
  },
  {
    id: 'lista-natal-do-senhor',
    titulo: 'Natal do Senhor',
    data: undefined,
    categoria: 'festas-liturgicas',
    musicas: [
      {
        id: 'm-a-festa-dos-dons-entrada',
        cifraId: 'a-festa-dos-dons',
        nome: 'A Festa Dos Dons',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-nasceu-hoje-em-belem-entrada',
        cifraId: 'nasceu-hoje-em-belem',
        nome: 'Nasceu Hoje Em Belém',
        autor: 'DANIEL DE ANGELES',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-nasceu-nos-hoje-entrada',
        cifraId: 'nasceu-nos-hoje',
        nome: 'Nasceu-Nos Hoje',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 2,
      },
      {
        id: 'm-a-palavra-se-fez-carne-ato-penitencial',
        cifraId: 'a-palavra-se-fez-carne',
        nome: 'A Palavra Se Fez Carne',
        autor: 'ADENOR LEONARDO TERRA',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-vou-levar-ronaldo-pelaquim-ato-penitencial',
        cifraId: 'vou-levar-ronaldo-pelaquim',
        nome: 'Vou Levar',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-alma-de-cristo-marcelo-oliveira-gloria',
        cifraId: 'alma-de-cristo-marcelo-oliveira',
        nome: 'Alma De Cristo',
        autor: 'MARCELO OLIVEIRA',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-o-luz-do-senhor-gloria',
        cifraId: 'o-luz-do-senhor',
        nome: 'Ó Luz Do Senhor',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-bendito-sejais-senhor-comunidade-recado-salmo',
        cifraId: 'bendito-sejais-senhor-comunidade-recado',
        nome: 'Bendito Sejais Senhor',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-gloria-a-deus-grupo-mensagem-ofertorio',
        cifraId: 'gloria-a-deus-grupo-mensagem',
        nome: 'Glória A Deus',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-longe-distante-de-casa-santo',
        cifraId: 'longe-distante-de-casa',
        nome: 'Longe Distante De Casa',
        autor: 'FREI FABRETTI',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-maria-anjo-comunhao',
        cifraId: 'maria-anjo',
        nome: 'Maria E O Anjo',
        autor: 'ANJOS DE RESGATE',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-noite-excelsa-comunidade-recado-comunhao',
        cifraId: 'noite-excelsa-comunidade-recado',
        nome: 'Noite Excelsa',
        autor: 'MARCELO OLIVEIRA (COMUNIDADE RECADO)',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-noite-feliz-comunhao',
        cifraId: 'noite-feliz',
        nome: 'Noite Feliz',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 2,
      },
      {
        id: 'm-gente-passa-o-ano-inteiro-assim-final',
        cifraId: 'gente-passa-o-ano-inteiro-assim',
        nome: 'A Gente Passa O Ano Inteiro Assim',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-aleluia-ao-deus-santo-final',
        cifraId: 'aleluia-ao-deus-santo',
        nome: 'Aleluia Ao Deus Santo',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 1,
      },
      {
        id: 'm-aleluia-quem-diria-frei-fabreti-final',
        cifraId: 'aleluia-quem-diria-frei-fabreti',
        nome: 'Aleluia! Quem Diria!',
        autor: 'FREI FABRETI',
        parte: 'final',
        ordem: 2,
      },
    ],
    criadaEm: '2025-01-01T00:00:00Z',
    atualizadaEm: '2025-01-01T00:00:00Z',
  },
  {
    id: 'lista-advento-–-vem,-senhor-jesus',
    titulo: 'Advento – Vem, Senhor Jesus',
    data: undefined,
    categoria: 'advento',
    musicas: [
      {
        id: 'm-nossa-oferta-apresentamos-entrada',
        cifraId: 'nossa-oferta-apresentamos',
        nome: 'A Nossa Oferta Apresentamos',
        autor: 'FREI JOEL POSTMA',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-senhor-nos-te-esperamos-entrada',
        cifraId: 'senhor-nos-te-esperamos',
        nome: 'Senhor Nós Te Esperamos',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-abencoa-ato-penitencial',
        cifraId: 'abencoa',
        nome: 'Abençoa',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-tempo-de-esperanca-e-de-viver-ato-penitencial',
        cifraId: 'tempo-de-esperanca-e-de-viver',
        nome: 'Tempo De Esperança E De Viver',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-ficai-atentos-e-orai-paulo-neto-gloria',
        cifraId: 'ficai-atentos-e-orai-paulo-neto',
        nome: 'Ficai Atentos E Orai',
        autor: 'Paulo Neto',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-teu-povo-senhor-gloria',
        cifraId: 'teu-povo-senhor',
        nome: 'Teu Povo, Senhor',
        autor: 'RICARDO SABINO',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-nasceu-em-belem-casa-pao-salmo',
        cifraId: 'nasceu-em-belem-casa-pao',
        nome: 'Nasceu Em Belém, A Casa Do Pão',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-vem-senhor-jesus-o-mundo-precisa-de-ti-salmo',
        cifraId: 'vem-senhor-jesus-o-mundo-precisa-de-ti',
        nome: 'Vem, Senhor Jesus, O Mundo Precisa De Ti!',
        autor: 'FR. ARI TOGNON',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-os-que-esperam-no-senhor-paulo-neto-ofertorio',
        cifraId: 'os-que-esperam-no-senhor-paulo-neto',
        nome: 'Os Que Esperam No Senhor',
        autor: 'PAULO NETO',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-e-dom-de-amor-ofertorio',
        cifraId: 'e-dom-de-amor',
        nome: 'É Dom De Amor',
        autor: 'IRMA MIRIA KOLLING',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-os-que-vos-esperam-o-senhor-cantando-antifonas-santo',
        cifraId: 'os-que-vos-esperam-o-senhor-cantando-antifonas',
        nome: 'Os Que Vos Esperam, Ó Senhor',
        autor: 'RUZYE (CANTANDO ANTÍFONAS)',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-pao-e-vinho-apresentamos-comunhao',
        cifraId: 'pao-e-vinho-apresentamos',
        nome: 'Pão E Vinho Apresentamos',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-da-cepa-brotou-rama-final',
        cifraId: 'da-cepa-brotou-rama',
        nome: 'Da Cepa Brotou A Rama',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-espera-o-povo-um-menino-grupo-opa-final',
        cifraId: 'espera-o-povo-um-menino-grupo-opa',
        nome: 'Espera O Povo Um Menino',
        autor: 'PE. IRALA · LUISINHO VIEIRA',
        parte: 'final',
        ordem: 1,
      },
      {
        id: 'm-luz-do-advento-final',
        cifraId: 'luz-do-advento',
        nome: 'Luz Do Advento',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 2,
      },
    ],
    criadaEm: '2025-01-01T00:00:00Z',
    atualizadaEm: '2025-01-01T00:00:00Z',
  },
  {
    id: 'lista-tempo-comum-–-repertório-completo',
    titulo: 'Tempo Comum – Repertório Completo',
    data: undefined,
    categoria: 'tempo-comum',
    musicas: [
      {
        id: 'm-a-alegria-esta-coracao-entrada',
        cifraId: 'a-alegria-esta-coracao',
        nome: 'A Alegria Está No Coração',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 0,
      },
      {
        id: 'm-bendito-sejais-coral-palestrina-entrada',
        cifraId: 'bendito-sejais-coral-palestrina',
        nome: 'Bendito Sejais',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 1,
      },
      {
        id: 'm-eis-aqui-senhor-entrada',
        cifraId: 'eis-aqui-senhor',
        nome: 'Eis-Me Aqui Senhor',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 2,
      },
      {
        id: 'm-hoje-e-tempo-de-louvar-entrada',
        cifraId: 'hoje-e-tempo-de-louvar',
        nome: 'Hoje É Tempo De Louvar',
        autor: 'Tradicional',
        parte: 'entrada',
        ordem: 3,
      },
      {
        id: 'm-a-mesa-santa-que-preparamos-ato-penitencial',
        cifraId: 'a-mesa-santa-que-preparamos',
        nome: 'A Mesa Santa Que Preparamos',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 0,
      },
      {
        id: 'm-bendito-sejais-senhor-ato-penitencial',
        cifraId: 'bendito-sejais-senhor',
        nome: 'Bendito Sejais, Senhor!',
        autor: 'PADRE JOSÉ WEBER',
        parte: 'ato-penitencial',
        ordem: 1,
      },
      {
        id: 'm-estar-em-tuas-maos-ato-penitencial',
        cifraId: 'estar-em-tuas-maos',
        nome: 'Estar Em Tuas Mãos',
        autor: 'COM. CATÓLICA SHALOM',
        parte: 'ato-penitencial',
        ordem: 2,
      },
      {
        id: 'm-louvai-padre-cleidimar-moreira-ato-penitencial',
        cifraId: 'louvai-padre-cleidimar-moreira',
        nome: 'Louvai',
        autor: 'Tradicional',
        parte: 'ato-penitencial',
        ordem: 3,
      },
      {
        id: 'm-a-palavra-de-deus-que-gera-a-vida-gloria',
        cifraId: 'a-palavra-de-deus-que-gera-a-vida',
        nome: 'A Palavra De Deus Que Gera A Vida',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 0,
      },
      {
        id: 'm-brilha-uma-luz-gloria',
        cifraId: 'brilha-uma-luz',
        nome: 'Brilha Uma Luz',
        autor: 'IRMÃ MIRIA KOLLING',
        parte: 'gloria',
        ordem: 1,
      },
      {
        id: 'm-eu-celebrarei-gloria',
        cifraId: 'eu-celebrarei',
        nome: 'Eu Celebrarei',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 2,
      },
      {
        id: 'm-mestre-onde-moras-gloria',
        cifraId: 'mestre-onde-moras',
        nome: 'Mestre, Onde Moras',
        autor: 'Tradicional',
        parte: 'gloria',
        ordem: 3,
      },
      {
        id: 'm-a-palavra-de-deus-e-luz-salmo',
        cifraId: 'a-palavra-de-deus-e-luz',
        nome: 'A Palavra De Deus É Luz',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 0,
      },
      {
        id: 'm-canto-louvores-ao-pai-salmo',
        cifraId: 'canto-louvores-ao-pai',
        nome: 'Canto Louvores Ao Pai',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 1,
      },
      {
        id: 'm-eu-e-minha-casa-serviremos-ao-senhor-salmo',
        cifraId: 'eu-e-minha-casa-serviremos-ao-senhor',
        nome: 'Eu E Minha Casa Serviremos Ao Senhor',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 2,
      },
      {
        id: 'm-missao-e-repertir-flavio-wozniack-salmo',
        cifraId: 'missao-e-repertir-flavio-wozniack',
        nome: 'Missão É Repartir',
        autor: 'Tradicional',
        parte: 'salmo',
        ordem: 3,
      },
      {
        id: 'm-a-hostia-sobre-o-altar-ofertorio',
        cifraId: 'a-hostia-sobre-o-altar',
        nome: 'A Hóstia Sobre O Altar',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 0,
      },
      {
        id: 'm-aviagem-ofertorio',
        cifraId: 'aviagem',
        nome: 'A Viagem',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 1,
      },
      {
        id: 'm-daqui-do-meu-lugar-ofertorio',
        cifraId: 'daqui-do-meu-lugar',
        nome: 'Daqui Do Meu Lugar',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 2,
      },
      {
        id: 'm-eis-os-dons-marcelo-oliveira-ofertorio',
        cifraId: 'eis-os-dons-marcelo-oliveira',
        nome: 'Eis Os Dons',
        autor: 'Tradicional',
        parte: 'ofertorio',
        ordem: 3,
      },
      {
        id: 'm-augusta-rainha-santo',
        cifraId: 'augusta-rainha',
        nome: 'Augusta Rainha',
        autor: 'ALINE BRASIL',
        parte: 'santo',
        ordem: 0,
      },
      {
        id: 'm-de-maos-estendidas-santo',
        cifraId: 'de-maos-estendidas',
        nome: 'De Mãos Estendidas',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 1,
      },
      {
        id: 'm-glorias-ao-rei-jesus-santo',
        cifraId: 'glorias-ao-rei-jesus',
        nome: 'Glórias Ao Rei Jesus',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 2,
      },
      {
        id: 'm-muitos-graos-de-trigo-santo',
        cifraId: 'muitos-graos-de-trigo',
        nome: 'Muitos Grãos De Trigo',
        autor: 'Tradicional',
        parte: 'santo',
        ordem: 3,
      },
      {
        id: 'm-bendigamos-ao-senhor-marcelo-oliveira-comunhao',
        cifraId: 'bendigamos-ao-senhor-marcelo-oliveira',
        nome: 'Bendigamos Ao Senhor',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 0,
      },
      {
        id: 'm-deixa-a-luz-do-ceu-entrar-comunhao',
        cifraId: 'deixa-a-luz-do-ceu-entrar',
        nome: 'Deixa A Luz Do Céu Entrar',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 1,
      },
      {
        id: 'm-grande-e-o-senhor-comunhao',
        cifraId: 'grande-e-o-senhor',
        nome: 'Grande É O Senhor',
        autor: 'Tradicional',
        parte: 'comunhao',
        ordem: 2,
      },
      {
        id: 'm-levanta-se-deus-miguel-arcanjo-ricardo-sabino-comunhao',
        cifraId: 'levanta-se-deus-miguel-arcanjo-ricardo-sabino',
        nome: 'Levanta-Se Deus',
        autor: 'Oração São Miguel Arcanjo',
        parte: 'comunhao',
        ordem: 3,
      },
      {
        id: 'm-bendito-seja-deus-final',
        cifraId: 'bendito-seja-deus',
        nome: 'Bendito Seja Deus',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 0,
      },
      {
        id: 'm-desde-o-nascer-ao-por-do-sol-final',
        cifraId: 'desde-o-nascer-ao-por-do-sol',
        nome: 'Desde O Nascer Ao Por Do Sol',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 1,
      },
      {
        id: 'm-deus-e-bom-e-fiel-final',
        cifraId: 'deus-e-bom-e-fiel',
        nome: 'Deus É Bom E Fiel',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 2,
      },
      {
        id: 'm-eu-te-exaltarei-meu-deus-final',
        cifraId: 'eu-te-exaltarei-meu-deus',
        nome: 'Eu Te Exaltarei Meu Deus',
        autor: 'Tradicional',
        parte: 'final',
        ordem: 3,
      },
    ],
    criadaEm: '2025-01-01T00:00:00Z',
    atualizadaEm: '2025-01-01T00:00:00Z',
  },
];

@Injectable({ providedIn: 'root' })
export class ListaMockRepository extends ListaRepository {
  private cifraRepo = inject(CifraRepository);
  private listas: Lista[] = this.carregarListas();

  private carregarListas(): Lista[] {
    try {
      const saved = localStorage.getItem(LS_ALL_KEY);
      if (saved) return JSON.parse(saved) as Lista[];
    } catch { }
    return [...MOCK_LISTAS];
  }

  private salvarLocal(): void {
    localStorage.setItem(LS_ALL_KEY, JSON.stringify(this.listas));
  }

  private enriquecerListas(listas: Lista[]): Observable<Lista[]> {
    return this.cifraRepo.getIndice().pipe(
      map((indice: CifraIndiceItem[]) => {
        const trechosMap = new Map<string, string>();
        indice.forEach((item: CifraIndiceItem) => {
          const words = item.letra.split(' ');
          const t = words.slice(0, 15).join(' ');
          trechosMap.set(item.id, t.length > 0 ? t + '...' : 'Trecho indisponível');
        });

        return listas.map(lista => ({
          ...lista,
          musicas: lista.musicas.map(m => ({
            ...m,
            trecho: m.trecho || trechosMap.get(m.cifraId) || 'Trecho indisponível'
          }))
        }));
      })
    );
  }

  override getListas(): Observable<Lista[]> {
    return this.enriquecerListas([...this.listas]);
  }

  override getListasDodia(data: string): Observable<ListasDoDiaResponse> {
    return this.enriquecerListas(this.listas.filter(l => l.data === data)).pipe(
      map((listas: Lista[]) => {
        return {
          listas: listas,
          assinaturaExpirada: (new Date().getTime() % 2) === 0
        }
      })
    );
  }

  override getListasPorCategoria(cat: CategoriaLiturgica): Observable<Lista[]> {
    return this.enriquecerListas(this.listas.filter(l => l.categoria === cat));
  }

  override getLista(id: string): Observable<Lista | undefined> {
    return this.enriquecerListas(this.listas.filter(l => l.id === id)).pipe(
      map(res => res[0])
    );
  }

  override salvarLista(lista: Lista): Observable<Lista> {
    const idx = this.listas.findIndex(l => l.id === lista.id);
    const updated = { ...lista, atualizadaEm: new Date().toISOString() };
    if (idx >= 0) {
      this.listas[idx] = updated;
    } else {
      this.listas.unshift(updated);
    }
    this.salvarLocal();
    return of(updated);
  }

  override excluirLista(id: string): Observable<void> {
    this.listas = this.listas.filter(l => l.id !== id);
    this.salvarLocal();
    return of(undefined);
  }

  resetMock(): void {
    this.listas = [...MOCK_LISTAS];
    localStorage.removeItem(LS_ALL_KEY);
  }
}
